### ISSUE TITLE
Entity no longer being provided by nationalrailuk integration

### ISSUE THREAD

**Issue by kev2024a** [jfparis/homeassistant_nationalrail#16]
HI, Receiving this error, having made no changes.

This entity is no longer being provided by the nationalrailuk integration. If the entity is no longer in use, delete it in settings.

Did something change?

Thanks

Kev

**Comment by percebefc** [comment]
Same issue here. It stopped working since last week

**Comment by skinnypope** [comment]
I updated to 2025.2 last night and got this same error "entity no longer being provided..."

I rolled back to 2025.1.4 and everything came back.

Maybe a coincidence as the two reports above seem unconnected to 2025.2 but it appears to be a breaking change for me?

**Comment by jfparis** [comment]
There was indeed an issue with home assistant 2025.2 that pulled a new version of httpx

I pushed a temporary fix in v0.3.5.

**Comment by skinnypope** [comment]
Excellent, safely installed and back working for me. Many thanks.

**Comment by jones-d** [comment]
Also fixed for me. Thank-you for the quick fix!

**Comment by kev2024a** [comment]
I'm running 2025.1.4 and still not working.... i have a option to update to 2025.2.0 but holding off.

Any suggestions on steps to fix?

Thanks

**Comment by jfparis** [comment]
Nope.
Maybe you could have a look at the logs and tell us what you see?

**Comment by kev2024a** [comment]
error on item shows "This entity is no longer being provided by the nationalrailuk integration. If the entity is no longer in use, delete it in settings."

I see this in the logs...
Setup failed for custom integration 'nationalrailuk': Unable to import component: No module named 'cgi'

Have upgraded, still no joy.

Thanks

**Comment by jfparis** [comment]
You are sending us the last line of the logs. There should be more (click
on the three dots and select show full logs)

That being said, the error message is very similar to something we fixed
back in December. Are you running the latest version of the integration?
--
Jean-François Paris
+44 7533414619

**Comment by jfparis** [comment]
Please use the latest version of HomeAssistant and the integration.

**Comment by kev2024a** [comment]
Hi, I'm running the lates HomeAssistant and HACs.

I've now updated the integration BUT I cannot add the custom card, clicking on the link and choosing to add by HACS, it just says it cannot find it and hence wont allow me to add it.

The existing sensor now shows a longnumber.shortnumber so I presume something has changed hence I was going to look at the custom card and see if its ok on that but unable to load it as it looks better than what I have at present.

Any ideas?

Thanks

**Comment by jfparis** [comment]
Dear Kev. 

I did not provide a custom card.  No idea where you took
This is not a support channel. Probably better discussed in the forum
